### ISSUE TITLE
Postgres issue in Ambarai

### ISSUE THREAD

**Issue by jwkidd3** [randerzander/docker-hdp#11]
seeing this:
Caused by: org.postgresql.util.PSQLException: ERROR: null value in column "cluster_host_info" violates not-null constraint
ambari-server.dev_1  |   Detail: Failing row contains (5, 2, null, 1494282593153, -1, 0, null, Install Components, INTERNAL_REQUEST, null, -1, null, null).

**Comment by devopsacid** [comment]
Same problem as I'm experiencing. 

I deployed new configuration and new docker containers and it's same problem.

**Comment by pmint93** [comment]
I also had the same issue

**Comment by devopsacid** [comment]
@jwkidd3 @pmint93 guys did you solve this issue somehow? I'm really interested in solution if you did so.

**Comment by pmint93** [comment]
@mmaxian I gave up on this. And I go straight to deploy a production hdp cluster by my self

**Comment by randerzander** [comment]
@pmint93 @mmaxian @jwkidd3 -- I was not able to resolve this issue until upgrading to the latest Ambari and HDP release (Friday, June 2, 2017).

Please try again after syncing with master, it's working for me now.
