### ISSUE TITLE
Ambar Server install error- scripts/start.sh: no such file or directory

### ISSUE THREAD

**Issue by murugan007** [randerzander/docker-hdp#12]
While trying to install Amabari server getting below error.
Step 6 : ADD scripts/start.sh /start.sh
scripts/start.sh: no such file or directory

Not sure if I am missing something.

**Comment by randerzander** [comment]
@murugan007 I believe you must have accidentally deleted the file from the project.

Try checking "git status" to see if it shows as removed. You can either "git checkout containers/ambari-server/scripts/start.sh", re-clone the project, or copy the file from https://github.com/randerzander/docker-hdp/blob/master/containers/ambari-server/scripts/start.sh
