### ISSUE TITLE
getting Error

### ISSUE THREAD

**Issue by hpvinod** [randerzander/docker-hdp#5]
We are getting below error:

postgres.dev_1       | FATAL:  role "ambari" does not exist

abari-server.dev_1   | No errors were found.
ambari-server.dev_1  | ERROR: Exiting with exit code 1
ambari-server.dev_1  | REASON: Database check failed to complete. Please check /var/log/ambari-server/ambari-server.log and /var/log/ambari-server/ambari-server-check-database.log for more information.

Also not able to open GUI http://localhost:8080

Thanks
Vinod

**Comment by sarath-mec** [comment]
Check the other issue with sed mentioned

**Comment by randerzander** [comment]
Thanks for the discussion, all. I believe I fixed this with the latest push to master with upgrade to HDP 2.6.

If you continue running into this problem, please re-open this or another issue.
